def build_markdown_report(event: dict, redacted_prompt: str,
                          owasp_controls: list[str], risk_reasons: list[str]) -> str:
    return "\n".join([
        f"# AI Security Incident Report — {event['event_id']}",
        "",
        f"- Timestamp: {event['timestamp']}",
        f"- Source: {event['source']}",
        f"- Decision: **{event['decision'].upper()}**",
        f"- Risk Score: **{event['risk_score']}/100**",
        "",
        "## Triggered Rules",
        *([f"- {x}" for x in event["triggered_rules"]] or ["- None"]),
        "",
        "## Sensitive Data Types",
        *([f"- {x}" for x in event["sensitive_types"]] or ["- None"]),
        "",
        "## OWASP LLM Security Mapping",
        *([f"- {x}" for x in owasp_controls] or ["- None"]),
        "",
        "## Risk Calculation",
        *([f"- {x}" for x in risk_reasons] or ["- No additional risk factors"]),
        "",
        "## Sanitized Prompt",
        "```text",
        redacted_prompt,
        "```",
        "",
        "## Analyst Notes",
        "- Validate whether the request was expected for the application context.",
        "- Review repeated source activity for abuse patterns.",
        "- Escalate blocked or high-risk requests according to the incident-response process.",
    ])
